import datetime
to_day = datetime.datetime.today()
print("Current Date and time :|:", to_day)
print("Current Date :|:", to_day.date())
print("Today's Date :|:", to_day.day)
print("Current Month :|:", to_day.month)
print("Current Year :|:", to_day.year)
print("Week of the day :|:", to_day.isoweekday())
print("Date 5 days back :|:", datetime.date.today() - datetime.timedelta(days=5))
print("Date 5 days after :|:", datetime.datetime.now() + datetime.timedelta(days=5))
print("Seconds remaining in my coming BDay :|:", (datetime.datetime(year=2021, month=10, day=4, hour=0, minute=0) - to_day).seconds)
print("Seconds consumed in running this program :|:", (datetime.datetime.today() - to_day).microseconds)
print("Current Time :|:", to_day.time())
print("Current Time minute", to_day.minute)
print("Current Time hour", to_day.hour)
print("Current Time seconds", to_day.second)
print("Current Time microseconds", to_day.microsecond)

# - datetime.datetime.now().time().microsecond)
